{
  config,
  lib,
  pkgs,
  # Provided by home-manager when it runs as a NixOS module (which is how every
  # host in this flake wires it up); `{ }` keeps the module usable standalone.
  osConfig ? { },
  ...
}:

let
  cfg = config.homeModules.hyprland;
  hostXkb = osConfig.services.xserver.xkb or { };
  stylix_theme = config.stylix.base16Scheme;
  inherit (lib)
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    ;

  # Wallpapers (used by hyprlock's background)
  path = ../wallpapers;
  files = builtins.attrNames (builtins.readDir path);
  format = (
    p:
    builtins.concatStringsSep "/" [
      (builtins.toString path)
      p
    ]
  );
  wallpapers = map format files;

  # Hyprland 0.55+ reads ~/.config/hypr/hyprland.lua natively (falling back to
  # the legacy hyprland.conf only when no .lua exists). The bulk of the config
  # lives as a real Lua file (./hyprland/hyprland.lua); only the per-host and
  # theme-dependent data is generated here into a `nix.lua` module that the Lua
  # config requires. The Hypr* tools (hyprlock/hypridle) still use hyprlang and
  # are configured separately below.

  # Turn each "output,mode,position,scale" monitor string into a Lua table entry.
  monitorEntries = lib.concatMapStringsSep ",\n" (
    m:
    let
      f = lib.splitString "," m;
    in
    ''{ output = "${lib.elemAt f 0}", mode = "${lib.elemAt f 1}", position = "${lib.elemAt f 2}", scale = "${lib.elemAt f 3}" }''
  ) cfg.monitors;

  # Generated Lua data module required by hyprland.lua as `require("nix")`.
  generatedLua = ''
    -- Generated by home/hyprland.nix. Do not edit by hand.
    return {
      monitors = {
    ${monitorEntries}
      },
      colors = {
        active_border = "rgb(${stylix_theme.base0E})",
        inactive_border = "rgb(${stylix_theme.base03})",
      },
      kb = {
        layout = "${cfg.xkb.layout}",
        variant = "${cfg.xkb.variant}",
        options = "${cfg.xkb.options}",
      },
    }
  '';
in
{
  options.homeModules.hyprland = {
    enable = mkEnableOption "Home manager settings for 'Hyprland'";

    monitors = mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "HDMI-A-1,highres,0x0,1.5"
      ];
    };

    # Hyprland does not read `services.xserver.xkb.*` -- it has its own `input`
    # block -- while the greeter and `console.useXkbConfig` read nothing else.
    # So the host's XKB settings are the single source of truth and these
    # default to them; set them only when Hyprland genuinely has to differ from
    # the host.
    #
    # A comma-separated `layout` is what makes layouts switchable: pair it with
    # a `grp:*` toggle in `options` (e.g. layout "us,br" plus
    # "grp:win_space_toggle") to cycle between them, as schonfinkel does. Hosts
    # with a single layout (euclid, br(thinkpad)) just leave the toggle out.
    xkb = {
      layout = mkOption {
        type = lib.types.str;
        default = hostXkb.layout or "us";
      };

      variant = mkOption {
        type = lib.types.str;
        default = hostXkb.variant or "";
      };

      options = mkOption {
        type = lib.types.str;
        default = hostXkb.options or "";
      };
    };

    hyprlock = {
      enable = mkEnableOption "Enable a custom 'hyprlock' configuration" // {
        default = true;
      };
    };

    wallpapers = mkOption {
      type = lib.types.listOf lib.types.path;
      default = wallpapers;
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      # The home-manager Hyprland module would write the legacy hyprland.conf;
      # we drive Hyprland with hyprland.lua instead, so it stays disabled.
      wayland.windowManager.hyprland.enable = false;

      # Real Lua config + the Nix-generated data module it requires.
      xdg.configFile."hypr/hyprland.lua".source = ./hyprland/hyprland.lua;
      xdg.configFile."hypr/nix.lua".text = generatedLua;
    }

    # Hyprlock Configuration
    (mkIf cfg.hyprlock.enable {
      programs.hyprlock = {
        enable = true;
        settings = {
          general = {
            disable_loading_bar = true;
            hide_cursor = true;
          };

          background = lib.mkForce [
            {
              monitor = "";
              path = builtins.head cfg.wallpapers;
              color = "rgb(${stylix_theme.base00})";
              blur_passes = 1;
              blur_size = 1;
              new_optimizations = true;
              ignore_opacity = false;
            }
          ];

          input-field = lib.mkOverride 10 [
            {
              monitor = "";
              size = "300, 50";
              outline_thickness = 2;
              fade_on_empty = false;
              placeholder_text = "<i>Enter Password</i>";
              dots_spacing = 0.2;
              dots_center = true;
              position = "0, 125";
              valign = "bottom";
              halign = "center";
            }
          ];

          label = [
            {
              monitor = "";
              text = "cmd[update:3600000] date +'%A, %B %d'";
              font_family = "GeistMono Nerd Font Propo Bold";
              font_size = 36;
              color = "rgb(${stylix_theme.base0E})";
              position = "0, -150";
              valign = "top";
              halign = "center";
            }
            {
              monitor = "";
              text = "$TIME";
              font_family = "GeistMono Nerd Font Propo Bold";
              font_size = 132;
              color = "rgb(${stylix_theme.base0E})";
              position = "0, -200";
              valign = "top";
              halign = "center";
            }
            {
              monitor = "";
              text = "   $USER";
              font_family = "GeistMono Nerd Font Propo Bold";
              font_size = 24;
              color = "rgb(${stylix_theme.base0E})";
              position = "0, 200";
              valign = "bottom";
              halign = "center";
            }
          ];
        };
      };

      services.hypridle = {
        enable = true;
        settings = {
          general = {
            lock_cmd = lib.getExe config.programs.hyprlock.package;
            before_sleep_cmd = "${pkgs.systemd}/bin/loginctl lock-session";
            after_sleep_cmd = ''hyprctl dispatch 'hl.dsp.dpms({ state = "on" })' '';
          };

          listener = [
            {
              timeout = 300;
              on-timeout = "${pkgs.systemd}/bin/loginctl lock-session";
            }
            {
              timeout = 330;
              on-timeout = ''hyprctl dispatch 'hl.dsp.dpms({ state = "off" })' '';
              on-resume = ''hyprctl dispatch 'hl.dsp.dpms({ state = "on" })' '';
            }
            {
              timeout = 600;
              on-timeout = "${pkgs.systemd}/bin/systemctl suspend";
            }
          ];
        };
      };

    })
  ]);
}
